"""Write scripts/README.md: every script with its purpose, worklog entry and command, read from its own header.

  uv run python scripts/make_scripts_index.py
"""

import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def header(path: Path) -> str:
    src = path.read_text()
    if path.suffix == ".py":
        return ast.get_docstring(ast.parse(src)) or ""
    return "\n".join(line.lstrip("#").strip() for line in src.splitlines()[1:15] if line.startswith("#"))


def first_paragraph(doc: str) -> str:
    para = []
    for line in doc.splitlines():
        if not line.strip() or line.strip().lower().startswith(("usage", "uv run")):
            break
        para.append(line.strip())
    return " ".join(para)


def usage(doc: str, path: Path) -> str:
    lines = doc.splitlines()
    for i, line in enumerate(lines):
        t = line.strip()
        if t.lower().startswith("usage:"):
            rest = t[6:].strip() or next((x.strip() for x in lines[i + 1:] if x.strip()), "")
            return re.sub(r"\s{2,}", " ", rest)
        if t.startswith(("uv run", "PYTORCH_", "scripts/")):
            return re.sub(r"\s{2,}", " ", t)
    return f"{path.relative_to(ROOT.parent)}" if path.suffix == ".sh" else ""


def entry(text: str) -> tuple[str, str]:
    """('E22n', rest) from 'E22n. What ...' / 'E24 (NEW APPROACH, ...), step 1: ...'."""
    m = re.match(r"(E\d+[a-z]?)\b(?:\s*\([^)]*\))?(?:,? step \d+)?(?: sweep)?[.:]?\s*", text)
    if not m:
        return "", text
    rest = text[m.end():]
    return m.group(1), rest[:1].upper() + rest[1:]


def order(e: str):
    m = re.match(r"E(\d+)([a-z]?)", e)
    return (int(m.group(1)), m.group(2)) if m else (999, "")


def cell(s: str) -> str:
    return s.replace("|", "\\|")


tools = [(f.name, first_paragraph(header(f)), usage(header(f), f)) for f in sorted(ROOT.glob("*.*"))
         if f.suffix in (".py", ".sh") and f.name != Path(__file__).name]
exps = []
for f in sorted((ROOT / "experiments").glob("*.*")):
    if f.suffix in (".py", ".sh"):
        e, what = entry(first_paragraph(header(f)))
        exps.append((e, f.name, what, usage(header(f), f)))
exps.sort(key=lambda r: (order(r[0]), r[1]))

out = [
    "# Scripts",
    "",
    "Generated by `uv run python scripts/make_scripts_index.py` from each script's own header (`head -30 <script>` shows the",
    "full description). Run every script from the repository root. Experiment scripts read captures from `captures/` (the data",
    "bundle) and write into `captures/<capture>/experiments/`; each belongs to the [WORKLOG](../docs/WORKLOG.md) entry in its",
    "first column.",
    "",
    "Notes:",
    "- `section.key=value` arguments override [config/default.yaml](../config/default.yaml) for that run (for example",
    "  `video.keyframes_per_room=16`).",
    "- **E24 (structure from motion)** needs `pycolmap` (installed by `uv sync` with the dev group). torch and pycolmap each",
    "  load their own OpenMP, so `e24_sfm_room.py` / `e24_sfm_flat.py` never import torch: they call `e24_export_model.py` as",
    "  a separate process when its export is missing.",
    "- **Legacy (VGGT, Depth Anything)**: `spike_phase0.py` and `portrait_rotation.py` need the `vggt` package, removed at the",
    "  MapAnything switch (D17): `git checkout 1d4eca8 && uv sync && uv run scan-fetch-weights --optional`.",
    "- `icp_refine.py` is a negative result (E14), kept for the record; the pipeline does not use it.",
    "",
    "## Tools",
    "",
    "| Script | What it does | Run |",
    "|---|---|---|",
    *[f"| `{n}` | {cell(w)} | `{cell(u)}` |" for n, w, u in tools],
    "",
    "## Experiments",
    "",
    "| Entry | Script | Question / what it does | Run |",
    "|---|---|---|---|",
    *[f"| {e or '–'} | `{n}` | {cell(w)} | " + (f"`{cell(u)}`" if u else "see the script header") + " |"
      for e, n, w, u in exps],
]
(ROOT / "README.md").write_text("\n".join(out) + "\n")
print(f"scripts/README.md: {len(tools)} tools, {len(exps)} experiment scripts")
